"""
Django settings for mandala project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if len(sys.argv) > 1 and sys.argv[1] == 'test':
    print("Starting in TEST mode")
    TEST = True
    DEV = False
elif len(sys.argv) > 1 and sys.argv[1] == 'runserver':
    print("Starting in DEV mode")
    DEV = True
    TEST = False
else:
    TEST = False
    DEV = False

if TEST:
    SECRET_KEY = 'testing'
else:
    SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1', '.mandalasinergia.eu']

# Application definition

INSTALLED_APPS = [
    'app',
    'bootstrap4',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'mandala.force_default_language_middleware.ForceDefaultLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mandala.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mandala.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

if TEST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST')
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# OpenID Connect (OIDC)

AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    # Needed to login by username in Django admin
    'django.contrib.auth.backends.ModelBackend',
    'mandala.oidc_authentication_backend.MyOIDCAB'
)

OIDC_RP_CLIENT_ID = os.getenv('OIDC_RP_CLIENT_ID')
OIDC_RP_CLIENT_SECRET = os.getenv('OIDC_RP_CLIENT_SECRET')
OIDC_OP_AUTHORIZATION_ENDPOINT = 'https://az.otselo.eu/auth/realms/zhiva-mrezha/protocol/openid-connect/auth'
OIDC_OP_TOKEN_ENDPOINT = 'https://az.otselo.eu/auth/realms/zhiva-mrezha/protocol/openid-connect/token'
OIDC_OP_USER_ENDPOINT = 'https://az.otselo.eu/auth/realms/zhiva-mrezha/protocol/openid-connect/userinfo'
LOGOUT_REDIRECT_URL = '/'
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_OP_JWKS_ENDPOINT = 'https://az.otselo.eu/auth/realms/zhiva-mrezha/protocol/openid-connect/certs'
OIDC_USER_ACCOUNT = 'https://az.otselo.eu/auth/realms/zhiva-mrezha/account'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'bg-bg'

LANGUAGES = (
    ('en', 'English'),
    ('bg', 'Бъларски')
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Model
AUTH_USER_MODEL = 'app.User'

# bootstrap4
BOOTSTRAP4 = {
    'theme_url': None
}

BOOTSTRAP4 = {
    "css_url": '/static/css/bootstrap.min.css',
    'javascript_url': '/static/js/bootstrap.min.js',
    'jquery_url': '/static/js/jquery-3.4.1.min.js',
    'jquery_slim_url': '/static/js/jquery-3.4.1.min.js',
    'popper_url': '/static/js/popper.min.js',
}
