- hosts: certificate
  vars:
    certbot_auto_renew_user: root
    certbot_auto_renew_hour: "5"
    certbot_auto_renew_minute: "20"
    certbot_create_if_missing: yes
    certbot_create_method: standalone
    certbot_admin_email: '{{ admin_email }}'
    certbot_certs: 
      - domains:
          - '{{ domain }}'
    certbot_create_standalone_stop_services:
      - nginx

  roles:
    - role: geerlingguy.certbot
      become: yes

  tasks:
    - name: create certbot webroot
      become: yes
      file:
        name: '{{ certbot_webroot }}'

