- hosts: all
  roles:
    - role: keycloak
      tags: keycloak

    - role: geerlingguy.nginx
      become: yes
      vars:
        nginx_remove_default_vhost: true
        nginx_vhosts:
          - listen: "443 ssl"
            server_name: "{{ domain }}"
            #root: '{{root}}'
            #error_page: ""
            #access_log: ""
            #error_log: ""
            state: "present"
            filename: "keycloak.conf"
            extra_parameters: |
              location '/.well-known/acme-challenge' {
                root        '{{ certbot_webroot }}';
              }
              location / {
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_pass http://127.0.0.1:8080;
              }

              ssl_certificate     /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;
              ssl_protocols       TLSv1.1 TLSv1.2;
              ssl_ciphers         HIGH:!aNULL:!MD5;

          - listen: "80"
            server_name: "{{ domain }}"
            return: "301 https://{{ domain }}$request_uri"
            filename: "keycloak.80.conf"
            state: "present"

      tags: nginx
